repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^thirdparty/
      - id: end-of-file-fixer
        exclude: ^thirdparty/
      - id: check-yaml
        exclude: ^thirdparty/
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^thirdparty/
        args: ["--profile", "black", "--filter-files", "--skip-glob=__init__.py"]
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        exclude: ^thirdparty/
        additional_dependencies:
          - "stylelint@16.10.0"
          - "stylelint-config-standard@35.0.0"
          - "stylelint-config-standard-scss@12.0.0"
          - "stylelint-order@6.0.4"
        args: ["--aei", "--"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: ^thirdparty/
  - repo: https://github.com/OCA/pylint-odoo
    rev: v9.0.4 # may be a tag or commit hash
    hooks:
      - id: pylint_odoo
        exclude: ^thirdparty/

  - repo: local
    hooks:
      # Prevent committing .rej files
      - id: forbidden-files
        name: forbidden files
        entry: found Copier update rejection files; review them and remove them
        language: fail
        files: "\\.rej$"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Prevent committing inline conflict markers
      - id: check-merge-conflict
        args: [--assume-in-merge]
  - repo: local
    hooks:
      - id: hitchhiker-modules-list
        name: hitchhiker modules list
        entry: hitchhiker modules list --save README.md
        always_run: true
        pass_filenames: false
        language: system
